vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "light"
vim.g.colors_name = "sf2-guile-light"
local colors = {
  background = "#e7e2d3",
  foreground = "#1b1e2d",
  cursor_bg = "#1b1e2d",
  cursor_fg = "#e7e2d3",
  selection_bg = "#1b1e2d",
  selection_fg = "#e7e2d3",
  panel_bg = "#dfdacc",
  sidebar_bg = "#e7e2d3",
  active_row_bg = "#d5d5c2",
  navigate_row_bg = "#e0d7c1",
  surface_dim = "#e3ded0",
  surface0 = "#d7d2c6",
  surface1 = "#cac7bc",
  overlay0 = "#8b8a88",
  overlay1 = "#6d6c6f",
  subtext = "#91908d",
  accent = "#537244",
  red = "#e8565f",
  green = "#6ecb78",
  yellow = "#f2b134",
  blue = "#4e91b4",
  magenta = "#c783d9",
  cyan = "#35c4c2",
  orange = "#dc8d55",
  normal_black = "#1b1e2d",
  normal_red = "#c34850",
  normal_green = "#4b8a52",
  normal_yellow = "#b38326",
  normal_blue = "#4682a2",
  normal_magenta = "#af73bf",
  normal_cyan = "#2ba19f",
  normal_white = "#dfdacc",
  bright_black = "#717073",
  bright_red = "#df535b",
  bright_green = "#5aa662",
  bright_yellow = "#dfa330",
  bright_blue = "#4c8eb0",
  bright_magenta = "#c380d5",
  bright_cyan = "#32b8b6",
  bright_white = "#cfcabf",
}
local highlights = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.panel_bg },
  Cursor = { fg = colors.background, bg = colors.cursor_bg },
  CursorLine = { bg = colors.surface0 },
  Visual = { bg = colors.selection_bg, fg = colors.selection_fg },
  Search = { bg = colors.yellow, fg = colors.background },
  IncSearch = { bg = colors.orange, fg = colors.background },
  StatusLine = { bg = colors.surface1, fg = colors.foreground },
  StatusLineNC = { bg = colors.surface0, fg = colors.subtext },
  WinSeparator = { fg = colors.surface1 },
  Pmenu = { bg = colors.panel_bg, fg = colors.foreground },
  PmenuSel = { bg = colors.selection_bg, fg = colors.selection_fg },
  LineNr = { fg = colors.overlay1 },
  CursorLineNr = { fg = colors.accent, bold = true },
  Comment = { fg = colors.subtext, italic = true },
  Constant = { fg = colors.cyan },
  String = { fg = colors.green },
  Number = { fg = colors.orange },
  Boolean = { fg = colors.orange },
  Identifier = { fg = colors.foreground },
  Function = { fg = colors.blue },
  Statement = { fg = colors.magenta },
  Keyword = { fg = colors.red },
  Type = { fg = colors.yellow },
  Special = { fg = colors.orange },
  Error = { fg = colors.red, bold = true },
  Todo = { fg = colors.background, bg = colors.yellow, bold = true },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.cyan },
  DiffAdd = { bg = colors.green, fg = colors.background },
  DiffChange = { bg = colors.blue, fg = colors.background },
  DiffDelete = { bg = colors.red, fg = colors.background },
  Terminal = { fg = colors.normal_white, bg = colors.background },
}
for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
