vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "sf2-akuma"
local colors = {
  background = "#0c0a12",
  foreground = "#fff4d6",
  cursor_bg = "#f2b134",
  cursor_fg = "#0c0a12",
  selection_bg = "#f2b134",
  selection_fg = "#0c0a12",
  panel_bg = "#16131a",
  sidebar_bg = "#0c0a12",
  active_row_bg = "#173e43",
  navigate_row_bg = "#3f2f19",
  surface_dim = "#0c0a12",
  surface0 = "#242126",
  surface1 = "#332f31",
  overlay0 = "#726c64",
  overlay1 = "#928b7e",
  subtext = "#b6ae9b",
  accent = "#e04020",
  red = "#e8565f",
  green = "#6ecb78",
  yellow = "#f2b134",
  blue = "#4aa5ff",
  magenta = "#c783d9",
  cyan = "#35c4c2",
  orange = "#e07038",
  normal_black = "#0c0a12",
  normal_red = "#e8565f",
  normal_green = "#6ecb78",
  normal_yellow = "#f2b134",
  normal_blue = "#4aa5ff",
  normal_magenta = "#c783d9",
  normal_cyan = "#35c4c2",
  normal_white = "#e2d8be",
  bright_black = "#68635c",
  bright_red = "#ec747c",
  bright_green = "#88d490",
  bright_yellow = "#f4bf59",
  bright_blue = "#6bb5ff",
  bright_magenta = "#d199e0",
  bright_cyan = "#59cfcd",
  bright_white = "#fffaf0",
}
local highlights = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.panel_bg },
  Cursor = { fg = colors.background, bg = colors.cursor_bg },
  CursorLine = { bg = colors.surface0 },
  Visual = { bg = colors.selection_bg, fg = colors.selection_fg },
  Search = { bg = colors.yellow, fg = colors.background },
  IncSearch = { bg = colors.orange, fg = colors.background },
  StatusLine = { bg = colors.surface1, fg = colors.foreground },
  StatusLineNC = { bg = colors.surface0, fg = colors.subtext },
  WinSeparator = { fg = colors.surface1 },
  Pmenu = { bg = colors.panel_bg, fg = colors.foreground },
  PmenuSel = { bg = colors.selection_bg, fg = colors.selection_fg },
  LineNr = { fg = colors.overlay1 },
  CursorLineNr = { fg = colors.accent, bold = true },
  Comment = { fg = colors.subtext, italic = true },
  Constant = { fg = colors.cyan },
  String = { fg = colors.green },
  Number = { fg = colors.orange },
  Boolean = { fg = colors.orange },
  Identifier = { fg = colors.foreground },
  Function = { fg = colors.blue },
  Statement = { fg = colors.magenta },
  Keyword = { fg = colors.red },
  Type = { fg = colors.yellow },
  Special = { fg = colors.orange },
  Error = { fg = colors.red, bold = true },
  Todo = { fg = colors.background, bg = colors.yellow, bold = true },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.cyan },
  DiffAdd = { bg = colors.green, fg = colors.background },
  DiffChange = { bg = colors.blue, fg = colors.background },
  DiffDelete = { bg = colors.red, fg = colors.background },
  Terminal = { fg = colors.normal_white, bg = colors.background },
}
for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
