schema_version = 1

[meta]
id = "balrog"
display_name = "Street Fighter II - Balrog"
kind = "character"
introduced_in = "champion-edition"
character = "Balrog"
aliases = ["boxer"]
name = "Balrog"
variant = "dark"
family = "sf2"
stage = "USA · Las Vegas marquee"

[ui]
background = "#191822"
surface = "#24232f"
overlay = "#32303e"
border = "#32303e"
foreground = "#d0cfdd"
muted = "#848297"
subtle = "#a6a4bc"
accent = "#d465a8"
accent_secondary = "#a5840e"
cursor = "#d465a8"
cursor_text = "#191822"
selection_background = "#4e2d40"
selection_foreground = "#d0cfdd"

[semantic]
red = "#c86d6e"
green = "#469760"
yellow = "#a28424"
blue = "#6187ce"
magenta = "#bd6e9c"
cyan = "#1194ad"
orange = "#c1753c"

[ansi.normal]
black = "#31303e"
red = "#c86d6e"
green = "#469760"
yellow = "#a28424"
blue = "#6187ce"
magenta = "#bd6e9c"
cyan = "#1194ad"
white = "#b4b3c1"

[ansi.bright]
black = "#848297"
red = "#ee8485"
green = "#57b575"
yellow = "#c29f30"
blue = "#76a2f5"
magenta = "#e185ba"
cyan = "#1bb2ce"
white = "#dadae5"
