schema_version = 1

[meta]
id = "cammy"
display_name = "Street Fighter II - Cammy"
kind = "character"
introduced_in = "super"
character = "Cammy"
aliases = []

[ui]
background = "#10180e"
foreground = "#fff4d6"
cursor_bg = "#f2b134"
cursor_fg = "#10180e"
selection_bg = "#f2b134"
selection_fg = "#10180e"
panel_bg = "#1a2116"
sidebar_bg = "#10180e"
active_row_bg = "#1a4840"
navigate_row_bg = "#423a16"
surface_dim = "#10180e"
surface0 = "#282e22"
surface1 = "#363b2e"
overlay0 = "#747462"
overlay1 = "#93917c"
subtext = "#b7b29a"
accent = "#477239"

[semantic]
red = "#e8565f"
green = "#5cb86a"
yellow = "#f2b134"
blue = "#4aa5ff"
magenta = "#c783d9"
cyan = "#35c4c2"
orange = "#dc8d55"

[ansi.normal]
black = "#10180e"
red = "#e8565f"
green = "#5cb86a"
yellow = "#f2b134"
blue = "#4aa5ff"
magenta = "#c783d9"
cyan = "#35c4c2"
white = "#e2dabe"

[ansi.bright]
black = "#6b6c5a"
red = "#ec747c"
green = "#79c585"
yellow = "#f4bf59"
blue = "#6bb5ff"
magenta = "#d199e0"
cyan = "#59cfcd"
white = "#fffaf0"
