schema_version = 1

[meta]
id = "cammy-light"
display_name = "Street Fighter II - Cammy Light"
kind = "character"
introduced_in = "super"
character = "Cammy"
aliases = []

[ui]
background = "#e7e2d1"
foreground = "#1b1e2d"
cursor_bg = "#1b1e2d"
cursor_fg = "#e7e2d1"
selection_bg = "#1b1e2d"
selection_fg = "#e7e2d1"
panel_bg = "#dfdaca"
sidebar_bg = "#e7e2d1"
active_row_bg = "#d4d5bf"
navigate_row_bg = "#e0d7c0"
surface_dim = "#e3dece"
surface0 = "#d7d2c4"
surface1 = "#cac7ba"
overlay0 = "#8b8a87"
overlay1 = "#6d6c6f"
subtext = "#91908c"
accent = "#477239"

[semantic]
red = "#e8565f"
green = "#5cb86a"
yellow = "#f2b134"
blue = "#4aa5ff"
magenta = "#c783d9"
cyan = "#35c4c2"
orange = "#dc8d55"

[ansi.normal]
black = "#1b1e2d"
red = "#c34850"
green = "#3f7d48"
yellow = "#b38326"
blue = "#4394e6"
magenta = "#af73bf"
cyan = "#2ba19f"
white = "#dfdaca"

[ansi.bright]
black = "#717072"
red = "#df535b"
green = "#4b9757"
yellow = "#dfa330"
blue = "#49a2fa"
magenta = "#c380d5"
cyan = "#32b8b6"
white = "#cfcabd"
