#!/usr/bin/env python3
"""Generate the committed single-file CLI from src/ and themes/."""

import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "sf2_theme"
OUT = ROOT / "sf2-themes"

MODULES: tuple[tuple[str, Path, bool], ...] = (
    ("sf2_theme", SRC / "__init__.py", True),
    ("sf2_theme.errors", SRC / "errors.py", False),
    ("sf2_theme.model", SRC / "model.py", False),
    ("sf2_theme.parse", SRC / "parse.py", False),
    ("sf2_theme.validation", SRC / "validation.py", False),
    ("sf2_theme.filesystem", SRC / "filesystem.py", False),
    ("sf2_theme.catalog", SRC / "catalog.py", False),
    ("sf2_theme.adapters", SRC / "adapters" / "__init__.py", True),
    ("sf2_theme.adapters.wezterm_lua", SRC / "adapters" / "wezterm_lua.py", False),
    ("sf2_theme.adapters.wezterm", SRC / "adapters" / "wezterm.py", False),
    ("sf2_theme.adapters.herdr", SRC / "adapters" / "herdr.py", False),
    ("sf2_theme.adapters.lazygit", SRC / "adapters" / "lazygit.py", False),
    ("sf2_theme.adapters.nvim", SRC / "adapters" / "nvim.py", False),
    ("sf2_theme.adapters.codex", SRC / "adapters" / "codex.py", False),
    ("sf2_theme.adapters.starship", SRC / "adapters" / "starship.py", False),
    ("sf2_theme.adapters.zsh_syntax", SRC / "adapters" / "zsh_syntax.py", False),
    ("sf2_theme.cli", SRC / "cli.py", False),
)


def theme_files() -> dict[str, str]:
    files = {"main.toml": (ROOT / "themes" / "main.toml").read_text(encoding="utf-8")}
    main_light = ROOT / "themes" / "main-light.toml"
    if main_light.is_file():
        files["main-light.toml"] = main_light.read_text(encoding="utf-8")
    for path in sorted((ROOT / "themes" / "characters").glob("*.toml")):
        files[f"characters/{path.name}"] = path.read_text(encoding="utf-8")
    return files


def render() -> str:
    modules = [(name, path.read_text(encoding="utf-8"), is_pkg) for name, path, is_pkg in MODULES]
    payload = {
        "themes": theme_files(),
        "modules": [(name, source, is_pkg) for name, source, is_pkg in modules],
    }
    return textwrap.dedent(
        """\
        #!/usr/bin/env python3
        # Generated by scripts/build-standalone.py. Do not edit by hand.
        from __future__ import annotations

        import sys
        import types

        _THEMES = {themes!r}
        _MODULES = {modules!r}

        def _install() -> None:
            embedded = types.ModuleType("sf2_theme._embedded")
            embedded.THEME_FILES = _THEMES
            sys.modules["sf2_theme._embedded"] = embedded
            for name, source, is_pkg in _MODULES:
                module = types.ModuleType(name)
                module.__file__ = f"<standalone:{{name}}>"
                module.__package__ = name if is_pkg else name.rpartition(".")[0]
                if is_pkg:
                    module.__path__ = []
                sys.modules[name] = module
                exec(compile(source, name, "exec"), module.__dict__)
                parent_name, dot, child = name.rpartition(".")
                if dot:
                    setattr(sys.modules[parent_name], child, module)

        _install()
        from sf2_theme.cli import main

        if __name__ == "__main__":
            raise SystemExit(main())
        """
    ).format(themes=payload["themes"], modules=payload["modules"])


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    OUT.chmod(OUT.stat().st_mode | 0o111)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
