"""zsh-syntax-highlighting styles derived from the active SF2 theme."""

import os
from pathlib import Path

from sf2_theme.filesystem import WriteResult, write_file
from sf2_theme.model import Theme


def highlight_path() -> Path:
    """Return the managed zsh-syntax-highlighting snippet path."""
    xdg = os.environ.get("XDG_CONFIG_HOME")
    root = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return root / "sf2-theme" / "zsh-syntax-highlighting.zsh"


def render_highlight(theme: Theme) -> str:
    """Render a sourcable zsh snippet that retints command highlights."""
    # Stock highlighter paints commands ANSI green. Remap the command family to
    # accent so typed commands track character identity with the Starship dirname.
    accent = theme.ui.accent
    secondary = theme.ui.accent_secondary
    muted = theme.ui.muted
    red = theme.semantic.red
    lines = [
        f"# sf2-themes: {theme.metadata.selectable_id}",
        "# Generated by sf2-themes. Source after zsh-syntax-highlighting.zsh.",
        "typeset -gA ZSH_HIGHLIGHT_STYLES",
        f"ZSH_HIGHLIGHT_STYLES[command]='fg={accent}'",
        f"ZSH_HIGHLIGHT_STYLES[arg0]='fg={accent}'",
        f"ZSH_HIGHLIGHT_STYLES[builtin]='fg={accent}'",
        f"ZSH_HIGHLIGHT_STYLES[precommand]='fg={secondary},underline'",
        f"ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={secondary},underline'",
        f"ZSH_HIGHLIGHT_STYLES[autodirectory]='fg={secondary},underline'",
        f"ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg={muted}'",
        f"ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg={muted}'",
        f"ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={red},bold'",
        "",
    ]
    return "\n".join(lines)


def apply_zsh_syntax(
    theme: Theme,
    *,
    dry_run: bool,
    follow_symlinks: bool,
) -> WriteResult:
    """Write the managed zsh-syntax-highlighting snippet."""
    return write_file(
        highlight_path(),
        render_highlight(theme),
        dry_run=dry_run,
        follow_symlinks=follow_symlinks,
    )


SOURCE_HINT = (
    '[[ -f "$HOME/.config/sf2-theme/zsh-syntax-highlighting.zsh" ]] && '
    'source "$HOME/.config/sf2-theme/zsh-syntax-highlighting.zsh"'
)
