vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "light"
vim.g.colors_name = "sf2-ryu-light"
local colors = {
  background = "#ecf1fa",
  foreground = "#2b313d",
  cursor_bg = "#ab4043",
  cursor_fg = "#ecf1fa",
  selection_bg = "#f4c9c6",
  selection_fg = "#2b313d",
  panel_bg = "#e1e7f2",
  sidebar_bg = "#ecf1fa",
  active_row_bg = "#f4c9c6",
  navigate_row_bg = "#d3dae8",
  surface_dim = "#ecf1fa",
  surface0 = "#e1e7f2",
  surface1 = "#d3dae8",
  overlay0 = "#d3dae8",
  overlay1 = "#5e6b83",
  subtext = "#424f68",
  accent = "#ab4043",
  red = "#a94a4b",
  green = "#3e7347",
  yellow = "#7b6600",
  blue = "#3169af",
  magenta = "#815893",
  cyan = "#0f7285",
  orange = "#9e5517",
  normal_black = "#363e4b",
  normal_red = "#a94a4b",
  normal_green = "#3e7347",
  normal_yellow = "#7b6600",
  normal_blue = "#3169af",
  normal_magenta = "#815893",
  normal_cyan = "#0f7285",
  normal_white = "#d9dee8",
  bright_black = "#4d5667",
  bright_red = "#9c3237",
  bright_green = "#236431",
  bright_yellow = "#685603",
  bright_blue = "#1257a4",
  bright_magenta = "#734587",
  bright_cyan = "#036071",
  bright_white = "#f1f5fa",
}
local highlights = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.panel_bg },
  Cursor = { fg = colors.background, bg = colors.cursor_bg },
  CursorLine = { bg = colors.surface0 },
  Visual = { bg = colors.selection_bg, fg = colors.selection_fg },
  Search = { bg = colors.yellow, fg = colors.background },
  IncSearch = { bg = colors.orange, fg = colors.background },
  StatusLine = { bg = colors.surface1, fg = colors.foreground },
  StatusLineNC = { bg = colors.surface0, fg = colors.subtext },
  WinSeparator = { fg = colors.surface1 },
  Pmenu = { bg = colors.panel_bg, fg = colors.foreground },
  PmenuSel = { bg = colors.selection_bg, fg = colors.selection_fg },
  LineNr = { fg = colors.overlay1 },
  CursorLineNr = { fg = colors.accent, bold = true },
  Comment = { fg = colors.subtext, italic = true },
  Constant = { fg = colors.cyan },
  String = { fg = colors.green },
  Number = { fg = colors.orange },
  Boolean = { fg = colors.orange },
  Identifier = { fg = colors.foreground },
  Function = { fg = colors.blue },
  Statement = { fg = colors.magenta },
  Keyword = { fg = colors.red },
  Type = { fg = colors.yellow },
  Special = { fg = colors.orange },
  Error = { fg = colors.red, bold = true },
  Todo = { fg = colors.background, bg = colors.yellow, bold = true },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.cyan },
  DiffAdd = { bg = colors.green, fg = colors.background },
  DiffChange = { bg = colors.blue, fg = colors.background },
  DiffDelete = { bg = colors.red, fg = colors.background },
  Terminal = { fg = colors.normal_white, bg = colors.background },
}
for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
