vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "sf2-main"
local colors = {
  background = "#131927",
  foreground = "#cad1de",
  cursor_bg = "#ad8705",
  cursor_fg = "#131927",
  selection_bg = "#453714",
  selection_fg = "#cad1de",
  panel_bg = "#1d2433",
  sidebar_bg = "#131927",
  active_row_bg = "#453714",
  navigate_row_bg = "#2a3243",
  surface_dim = "#131927",
  surface0 = "#1d2433",
  surface1 = "#2a3243",
  overlay0 = "#2a3243",
  overlay1 = "#7c8597",
  subtext = "#9ca7bd",
  accent = "#ad8705",
  red = "#c86e67",
  green = "#4e975b",
  yellow = "#a58324",
  blue = "#5b89cc",
  magenta = "#b371ad",
  cyan = "#1396a1",
  orange = "#c1753c",
  normal_black = "#2b323f",
  normal_red = "#c86e67",
  normal_green = "#4e975b",
  normal_yellow = "#a58324",
  normal_blue = "#5b89cc",
  normal_magenta = "#b371ad",
  normal_cyan = "#1396a1",
  normal_white = "#aeb5c2",
  bright_black = "#7c8597",
  bright_red = "#ee857d",
  bright_green = "#60b46f",
  bright_yellow = "#c59e30",
  bright_blue = "#6ea4f3",
  bright_magenta = "#d589cf",
  bright_cyan = "#1db3c0",
  bright_white = "#d6dbe5",
}
local highlights = {
  Normal = { fg = colors.foreground, bg = colors.background },
  NormalFloat = { fg = colors.foreground, bg = colors.panel_bg },
  Cursor = { fg = colors.background, bg = colors.cursor_bg },
  CursorLine = { bg = colors.surface0 },
  Visual = { bg = colors.selection_bg, fg = colors.selection_fg },
  Search = { bg = colors.yellow, fg = colors.background },
  IncSearch = { bg = colors.orange, fg = colors.background },
  StatusLine = { bg = colors.surface1, fg = colors.foreground },
  StatusLineNC = { bg = colors.surface0, fg = colors.subtext },
  WinSeparator = { fg = colors.surface1 },
  Pmenu = { bg = colors.panel_bg, fg = colors.foreground },
  PmenuSel = { bg = colors.selection_bg, fg = colors.selection_fg },
  LineNr = { fg = colors.overlay1 },
  CursorLineNr = { fg = colors.accent, bold = true },
  Comment = { fg = colors.subtext, italic = true },
  Constant = { fg = colors.cyan },
  String = { fg = colors.green },
  Number = { fg = colors.orange },
  Boolean = { fg = colors.orange },
  Identifier = { fg = colors.foreground },
  Function = { fg = colors.blue },
  Statement = { fg = colors.magenta },
  Keyword = { fg = colors.red },
  Type = { fg = colors.yellow },
  Special = { fg = colors.orange },
  Error = { fg = colors.red, bold = true },
  Todo = { fg = colors.background, bg = colors.yellow, bold = true },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.cyan },
  DiffAdd = { bg = colors.green, fg = colors.background },
  DiffChange = { bg = colors.blue, fg = colors.background },
  DiffDelete = { bg = colors.red, fg = colors.background },
  Terminal = { fg = colors.normal_white, bg = colors.background },
}
for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
